### PR TITLE
fix: added missing styles to confirm page

### PR DESCRIPTION
**Pull request by elpollo12**
### Description

Added missing styles to confirm page

fixes # (issue)

#43 

#### Screenshots
scrnli_6_11_2021 10-44-06

scrnli_6_11_2021 10-44-51

### CODE REVIEW

**Comment by elpollo12** [comment]
The modification in rating styled is to solve the problem in firefox

**Comment by Israel-Laguan** [comment]
I tested but doesn't see much change, please check @elpollo12 
image

**Comment by heliomar-pena** [comment]
@Israel-Laguan 

I already see the change at the [netlify preview](https://deploy-preview-133--azordev-dasher-user.netlify.app/confirm/test), but can't see the change in rating component

imagen

**Comment by Israel-Laguan** [comment]
> @Israel-Laguan
> 
> I already see the change at the [netlify preview](https://deploy-preview-133--azordev-dasher-user.netlify.app/confirm/test), but can't see the change in rating component

What I did was running locally changing the modal state here

image

result in firefox:
image
image
image
image

**Review by Israel-Laguan — APPROVED** [review]

**Pull request merged**
