### PR TITLE
Added issue and pull request template

### LINKED ISSUE #82: Add issue and pull request templates
To help the developer create clear issues and pull requests easily, we can add issue templates and pull request templates to the repository. 

### References
https://docs.github.com/es/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

### PR DESCRIPTION
**Pull request by heliomar-pena**
### Description

I have added some templates for organizate a little more the project and to ease the way to create Pull Request and Issues.

fixes #82 

#### Screenshots

When it merges, that should look like:
imagen
When you want create a issue, allowing you to select the template that you consider appropriate for the issue

PD: The Pull Request template look like this

#### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] Doesn't break the current code.
- [x] Passes linters and test, also is building.
- [x] Doesn't have spelling or grammatical problems.
- [x] Doesn't have unnecessary comments or debugging code.
- [x] The branch is updated with the last dev branch changes.

### CODE REVIEW

**Comment by heliomar-pena** [comment]
@Israel-Laguan It will work if is in dev branch instead main branch?

**Review by Israel-Laguan — APPROVED** [review]

**Comment by Israel-Laguan** [comment]
default branch here is dev so I think should work, lets see when is merged

**Comment by AlejandroSalcido** [comment]
Great information, taking on consideration before making new pull request!

**Review by ginnaaceror — APPROVED** [review]
Great @Katsu08!

**Pull request merged**
