### PR TITLE
feature/#22-add-button-component

### LINKED ISSUE #22: Add Button Component
Instances presented in Design (#2):

image
image
image
image
image
image
image
image
image

Notice:
- Can have a shadow
- Can expand to cover 100% horizontally
- Can have icons
- Can change color and background colors
- Can have icons and text

## Related issues

- #23

### PR DESCRIPTION
**Pull request by AlejandroSalcido**
Please review button re usability, you can add the name on every different button you add

### CODE REVIEW

**Comment by Israel-Laguan** [comment]
Why do you have changes on your yarn.lock?

**Review by ginnaaceror — COMMENTED** [review]
This branch have conflicts.

**Comment by ginnaaceror** [comment]
Hi @Israel-Laguan this branch has no conflicts now but the button component is not in use.

**Comment by AlejandroSalcido** [comment]
> Hi @Israel-Laguan this branch has no conflicts now but the button component is not in use.

@ginnaaceror  Hi Ginna, hope you're  doing great!
if you want to watch how the components actually look, you just need to place it on whatever part of the visible code that you like, just import the component and use the right branch for every component.
if you got any doubt please let me know!

**Comment by heliomar-pena** [comment]
What do you think about adding screenshot in the description? would be a good way to show the visual changes without add extra code @AlejandroSalcido

**Pull request merged**
