### PR TITLE
Fixed styles on Confirm Modal

### LINKED ISSUE #151: Modal "Que tal tu experiencia": Customer changes
### Explanation

The client left some comments about the design of the modality "How about your experience?"

### Screenshots

imagen

### Checklist

This issue can be closed when the following tasks are completed:

- [x] Please change the position of the subtitle and title, put the subtitle on the top and the title under the subtitle
- [x] The subtitle is not so separated 
- [x] The subtitle have a stronger color
- [x] The subtitle is bolder

### PR DESCRIPTION
**Pull request by heliomar-pena**
### Description

I have fixed the styles on confirm modal. I have changed the position of subtitle and title, and change the color of subtitle and the weight of text.

I have fixed a bug, the paragraph that are in the modal <InfoContainer> only was be gray, I have fixed this bug deleting that line and checked and the others modals now have the color that should have 

fixes #151

#### Screenshots

imagen

#### Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Checklist:

- [x] Please change the position of the subtitle and title, put the subtitle on the top and the title under the subtitle
- [x] The subtitle is not so separated 
- [x] The subtitle have a stronger color
- [x] The subtitle is bolder

### CODE REVIEW

**Review by Israel-Laguan — APPROVED** [review]

**Comment by Israel-Laguan** [comment]
@angelik0828 please check responsiveness.

**Comment by heliomar-pena** [comment]
you can test using this link https://dasheruser.katsu08.repl.co/confirm/751f5ea3-f005-4dd9-b24e-5a779a208270

**Comment by angelik0828** [comment]
Once the resolutions have been revised, I think the text should be larger, at least the two that go before the question, and in smaller resolutions the text of these should be centered.  @Katsu08 

image
image

**Comment by Israel-Laguan** [comment]
@Katsu08 please check @angelik0828 comment

**Review by Israel-Laguan — APPROVED** [review]

**Review by angelik0828 — APPROVED** [review]

**Pull request merged**
